baseURL = "https://zen-swirles-589a00.netlify.app/"
languageCode = "en-us"
title = "ICT 302" 
theme = "hugo-theme-m10c-master" 
[params]
description = "Student at Univsersity of Kentucky, ICT major Business minor"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"


[[menu.main]]
name = "Introduction"
weight = 1
url = "/introduction/"

[[menu.main]]
name = "Definition"
weight = 2
url = "/definition/"

[[menu.main]]
name = "Resource"
weight = 3
url = "/resource/" 

[[menu.main]]
name = "Walkthrough"
weight = 4
url = "/walkthrough/" 







  
