baseURL = "https://example.com"
title = "Your title"
themesDir = "../.."
theme = "m10c"
paginate = 5

[params]
  author = "John Doe"
  description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vehicula turpis sit amet elit pretium."
  [[params.social]]
    name = "instagram"
    url = "https://github.com/gohugoio"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/gohugoio"

  # Brown theme
  #[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"
  
  # Green theme
  #[params.style]
   darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"

  # Red and black theme
  #[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"
