baseURL = "/"
title = "ICT 302"
theme = "m10c"
paginate = 5 

$ cd [path]
$ git clone https://github.com/vaga/hugo-theme-m10c.git themes/m10c

[params]
  author = "john doe"
  description = "University of asgard"
  [[params.social]]
    name = "instagram"
    url = "https://github.com/gohugoio"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/gohugoio"

  # Brown theme
  #[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"
  
  # Green theme
  #[params.style]
   darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"

  # Red and black theme
  #[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"
